### ISSUE TITLE
Wrong jsonschema requirement in PyPi

### ISSUE THREAD

**Issue by vinci1it2000** [JRCSTU/wltp#6]
<img width="1139" alt="Screenshot 2019-09-20 at 11 26 53" src="https://user-images.githubusercontent.com/11716821/65316088-8f2bc380-db99-11e9-9f1b-87ecb3177eea.png">

**Comment by ankostis** [comment]
Why it's it wrong?

**Comment by vinci1it2000** [comment]
You have not any limitation in the [setup](https://github.com/JRCSTU/wltp/blob/master/setup.py#L222) file, but when it is installed from PyPI it downgrades the `jsonschema`  to `2.6.0`.  Moreover, this version is icompatible with `pandalone` that requires `jsonschema >=3.0.0`.

**Comment by ankostis** [comment]
The latest sources in wltp repo are not released yet because the project is not ready. The only release in PyPiv is the one code.

The old wltp depend on jsonschema-w.
The new (unreleased) on 3.

Pandalone had 2 active releases, one for 2 and another for 3: https://pypi.org/project/pandalone/#history

So make sure you have this boundary as co2mpas dependency: wltp < 1

This will pick the correct pandalone.

**Comment by vinci1it2000** [comment]
@ankostis can you check what you wrote? the latest version of wltp is 0.1.2a0 so if we put wltp < 1 doesn't change anything.

**Comment by ankostis** [comment]
You're right.  
I forgot that `wltp < 1` did not depend on `pandalone` at all, so you have to set also the boundary for `pandalone < 0.3` in `co2mpas:setup.py`.
